spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: scasproject66@gmail.com
    password: bdwtvnamymnmzxgz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
minio:
  url: http://minio:4000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: avatars
security:
  jwt:
    secret: ZGhhc2xhc2Roc2FsZGhhc2Rhc2RrbGQvc2hhc2RoOz9BZGFzZDMyZWRzYw==
    access: 3600000
    refresh: 2592000000