spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: scasproject66@gmail.com
    password: bdwtvnamymnmzxgz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true