version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":4001"