spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max:
          request:
            size: 2097152
        enable:
          idempotence: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: report-created-events
      properties:
        spring.json.trusted.packages: "*"
management:
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

datasource:
  url: jdbc:h2:mem:testdb
  username: admin
  password: admin
h2:
  console:
    enabled: true
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8082
